import "@/app/_styles/index.scss";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import TokenContextProvider from "./_context/token.context";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700", "900"]
});

export const metadata: Metadata = {
    title: "%s | Proyecto Next",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                <TokenContextProvider>
                    <header>
                        <nav>Navbar Testing</nav>
                    </header>

                    {children}
                </TokenContextProvider>
            </body>
        </html>
    );
}
